- op: replace
  path: /apiVersion
  value: apps/v1
- op: replace
  path: /kind
  value: Deployment
- op: remove
  path: /spec/strategy
- op: add
  path: /spec/selector
  value:
    matchLabels:
      app: ml-server
- op: replace
  path: /spec/replicas
  value: 1
- op: replace
  path: /spec/template/spec/containers/0/securityContext/readOnlyRootFilesystem
  value: false
- op: add
  path: /spec/template/spec/initContainers
  value:
    - name: migrate
      image: igorsantarek/ml_server:latest
      command: ["/app/.venv/bin/alembic", "upgrade", "head"]
      env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cnpg-cluster-app
              key: uri
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
        readOnlyRootFilesystem: true
      volumeMounts:
        - name: tmp
          mountPath: /tmp
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: HOSTNAME
    value: ml-server-dev
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: SMTP_HOST
    value: mailpit
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: SMTP_PORT
    value: "1025"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: SMTP_USE_CREDENTIALS
    value: "false"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: SMTP_VALIDATE_CERTS
    value: "false"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: SMTP_FROM
    value: no-reply@example.com
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: SMTP_STARTTLS
    value: "false"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: SMTP_SSL_TLS
    value: "false"