- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: ENV
    value: production
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: HOSTNAME
    value: http://ml-server-production.com
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FRONTEND_HOSTNAME
    value: http://ml-server-production.com
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: GOOGLE_OAUTH2_CREDS__CLIENT_ID
    value: 103419354438-hgqip1ac5oibmo0vtq68d53japlj409g.apps.googleusercontent.com
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: GITHUB_OAUTH2_CREDS__CLIENT_ID
    value: Ov23liN9y4yqkCuQWfkK