# https://taskfile.dev

version: '3'

includes:
  utils:
    taskfile: ../utils/Taskfile.yml

tasks:
  trigger-build-push:
    desc: "Trigger the Build & Push Docker image workflow"
    cmds:
      - |
        act push \
          --container-architecture linux/amd64 \
          --secret-file .github/workflows/build-push/secrets.json \
          -e .github/workflows/build-push/build-push-event.json \
          -P ubuntu-latest=catthehacker/ubuntu:act-22.04 \
          -W .github/workflows/build-push.yml
