apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-server
  namespace: mlops-project
  labels:
    app: ml-server
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: mlops-container
          image: igorsantarek/ml_server:0.8.3
