# https://taskfile.dev

version: '3'

tasks:
  run-dev:
    desc: Run the development server
    env:
      VITE_BACKEND_URL: http://localhost:8000
    cmds:
      - npm run dev
  build:
    desc: Build the frontend application
    cmds:
      - npm run build
  build-image:
    desc: Build the frontend docker image
    cmds:
      - docker build -t {{.FRONTEND_IMAGE_REPO}}:latest .
  run-docker:
    desc: Run the frontend container locally
    cmds:
      - docker run -d -p 3000:3000 {{.FRONTEND_IMAGE_REPO}}:latest
  push-image:
    desc: Push the frontend docker image to registry
    cmds:
      - docker push {{.FRONTEND_IMAGE_REPO}}:latest