repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: kluctl-validate
        name: Kluctl validate
        entry: devbox run -- kluctl validate
        language: system
        pass_filenames: false
        files: ^k8s/\.(yaml|yml)$
        exclude: Taskfile\.(yaml|yml)$
-   repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
-   repo: https://github.com/pycqa/flake8
    rev: '7.3.0'
    hooks:
    -   id: flake8
