# https://taskfile.dev

version: '3'

vars:
  SERVER_IMAGE_REPO: "igorsantarek/ml_server"
  FRONTEND_IMAGE_REPO: "igorsantarek/frontend"

includes:
  ml_server:
    taskfile: ml_server/Taskfile.yaml
    dir: ml_server
  frontend:
    taskfile: frontend/Taskfile.yml
    dir: frontend
  k8s:
    taskfile: k8s/Taskfile.yaml
    dir: k8s
  utils:
    taskfile: utils/Taskfile.yaml
    dir: utils
  build-push-wf:
    taskfile: .github/workflows/build-push/Taskfile.yml
  test-wf:
    taskfile: .github/workflows/test/Taskfile.yml
  terraform:
    taskfile: terraform/Taskfile.yml
    dir: terraform

tasks:
  tilt-up:
    desc: "Start Tilt for local Kubernetes development"
    cmds:
      - tilt up
  sync-repo-deps:
    desc: "Sync repo dependencies"
    cmds:
      - uv lock
      - uv sync
  sync-server-deps:
    desc: "Sync server dependencies"
    dir: ml_server
    cmds:
      - uv lock
      - uv sync
  sync-deps:
    desc: "Sync all dependencies"
    deps:
      - sync-repo-deps
      - sync-server-deps
  lock-deps:
    desc: "Lock all dependencies"
    cmds:
      - uv lock
      - uv lock --project ml_server
  lint:
    desc: "Run linters for all components"
    cmds:
      # stop the build if there are Python syntax errors or undefined names
      - uv run flake8 ml_server/src --count --select=E9,F63,F7,F82 --show-source --statistics
      # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      - uv run flake8 ml_server/src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
