targets:
  - name: staging
    context: kind-kind-staging
    args:
      environment: staging
  - name: production
    context: kind-kind-production
    args:
      environment: production

args:
  - name: environment
    default: staging

discriminator: mlops-project-{{ target.name }}
