apiVersion: gitops.kluctl.io/v1beta1
kind: KluctlDeployment
metadata:
  name: gitops
  namespace: kluctl-gitops
spec:
  interval: 5m
  source:
    git:
      url: https://github.com/jegor377/mlops-project.git
      path: k8s/kluctl-gitops
  credentials:
    git:
      - host: github.com
        secretRef:
          name: github-auth
  target: {{ args.cluster_name }}
  args:
    cluster_name: {{ args.cluster_name }}
  context: default
  prune: true
  delete: true
