version: '3'

tasks:
  create-cluster:
    desc: "Create the kind cluster"
    cmds:
      - kind create cluster --config kind-config.yaml
      - task: install-argocd
      - task: apply-crds
      - task: apply-root-app
  delete-cluster:
    desc: "Delete the kind cluster"
    cmds:
      - kind delete cluster
  port-forward:
    desc: "Port forward the Traefik gateway to localhost"
    cmds:
      - kubectl -n traefik port-forward svc/traefik 80
  install-argocd:
    desc: "Install Argo CD in the cluster"
    cmds:
      - kubectl create namespace argocd
      - kubectl apply -n argocd --server-side --force-conflicts -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  apply-crds:
    desc: "Apply the CRDs for Argo CD applications"
    cmds:
      - kubectl apply -f crds/gateway-api-crds.yaml
  apply-root-app:
    desc: "Apply the root Argo CD application"
    cmds:
      - kubectl apply -f argocd/app-project.yaml
      - kubectl apply -f argocd/app-project-ml-server.yaml
      - kubectl apply -f argocd/root-app.yaml
  get-argocd-pw:
    desc: "Get the initial admin password for Argo CD"
    cmds:
      - argocd admin initial-password -n argocd
  open-argocd-ui:
    desc: "Open the Argo CD UI in the browser"
    cmds:
      - kubectl port-forward svc/argocd-server -n argocd 8080:443