version: '3'

tasks:
  port-forward-traefik:
    desc: "Port forward the Traefik gateway to localhost"
    watch: true
    cmds:
      - kubectl -n traefik-system port-forward svc/traefik 80
  port-forward-psql:
    desc: "Port forward the postgres service to localhost"
    watch: true
    cmds:
      - kubectl -n ml-server-dev port-forward svc/cnpg-cluster-rw 8082:5432
  port-forward-mailpit:
    desc: "Port forward the Mailpit service to localhost"
    watch: true
    cmds:
      - kubectl -n ml-server-dev port-forward svc/mailpit 8026:8025
  port-forward-redis:
    desc: "Port forward the Redis service to localhost"
    watch: true
    cmds:
      - kubectl -n redis-system port-forward svc/bitnami-redis-master 6379
  port-forward:
    desc: "Port forward multiple services to localhost"
    deps:
      - port-forward-traefik
      - port-forward-psql
      - port-forward-mailpit
      - port-forward-redis
  apply-dev-resources:
    desc: "Apply development resources to the cluster"
    cmds:
      - kubectl apply -k services/ml_server/overlays/dev
      - |
        kubectl get secret bitnami-redis -n redis-system -o yaml \
        | sed 's/namespace: redis-system/namespace: ml-server-dev/' \
        | kubectl apply -n ml-server-dev -f -
      - kubectl apply -k services/frontend/overlays/dev
  delete-dev-resources:
    desc: "Delete development resources from the cluster"
    cmds:
      - kubectl delete -k services/ml_server/overlays/dev
      - kubectl delete -k services/frontend/overlays/dev
  install-argo-rollouts-plugin:
    desc: "Install the Argo Rollouts plugin for Argo CD"
    cmds:
      - curl -LO https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-linux-amd64
      - chmod +x ./kubectl-argo-rollouts-linux-amd64
      - sudo mv ./kubectl-argo-rollouts-linux-amd64 /usr/local/bin/kubectl-argo-rollouts
      - kubectl argo rollouts version
  apply-root-app:
    desc: "Apply the root Argo CD application"
    cmds:
      - kubectl apply -f argocd/app-project-ml-server.yaml
      - kubectl apply -f argocd/app-project-frontend.yaml
      - kubectl apply -f argocd/root-app.yaml
  get-argocd-pw:
    desc: "Get the initial admin password for Argo CD"
    cmds:
      - argocd admin initial-password -n argocd
  open-argocd-ui:
    desc: "Open the Argo CD UI in the browser"
    cmds:
      - kubectl port-forward svc/argocd-server -n argocd 8080:443
  open-argo-rollouts-ui:
    desc: "Open the Argo Rollouts UI in the browser"
    cmds:
      - kubectl argo rollouts dashboard
  run-lb-gw:
    desc: "Run the Cloud Provider Kind load balancer for Gateway API"
    cmds:
      - cloud-provider-kind --gateway-channel standard
  test-dev-env-ping:
    vars:
      IP: "172.18.0.5"
    desc: "Test the ping endpoint of the ML server"
    cmds:
      - |
        curl -H "Host: ml-server-dev" http://{{.IP}}/ping
        printf "\n"
  add-gcloud-kubectx:
    desc: "Add gcloud context to kubectl"
    cmds:
      - gcloud container clusters get-credentials ml-server-cluster --zone us-central1-a
  kind-load-ml-server-image:
    desc: "Load the ML server Docker image into the Kind cluster"
    cmds:
      - kind load docker-image {{.SERVER_IMAGE_REPO}}:latest --name dev-cluster
  kind-load-frontend-image:
    desc: "Load the frontend Docker image into the Kind cluster"
    cmds:
      - kind load docker-image {{.FRONTEND_IMAGE_REPO}}:latest --name dev-cluster
  kind-load-imgs:
    desc: "Load the ML server Docker image into the Kind cluster"
    deps:
      - kind-load-ml-server-image
      - kind-load-frontend-image
  psql-k8s-dev:
    desc: "Connect to the Postgres instance running in the dev Kubernetes environment"
    cmds:
      - |
        PSQL_URI=$(kubectl get secret cnpg-cluster-app -o yaml | yq ".data.uri" | base64 -d)
        PSQL_URI=$(sed 's/cnpg-cluster-rw.ml-server-dev:5432/127.0.0.1:8082/' <<< "$PSQL_URI")
        psql "$PSQL_URI"