version: '3'

tasks:
  create-cluster:
    desc: "Create the kind cluster"
    cmds:
      - kind create cluster --config kind-config.yaml
      - task: install-argocd
      - task: install-argo-rollouts
      - task: apply-crds
      - printf "Next steps:\n\ntask k8s:install-argo-rollouts-plugin\ntask k8s:apply-root-app\ntask k8s:get-argocd-pw\ntask k8s:open-argocd-ui\n"
  delete-cluster:
    desc: "Delete the kind cluster"
    cmds:
      - kind delete cluster
  port-forward:
    desc: "Port forward the Traefik gateway to localhost"
    cmds:
      - kubectl -n traefik port-forward svc/traefik 80
  install-argocd:
    desc: "Install Argo CD in the cluster"
    cmds:
      - kubectl create namespace argocd
      - kubectl apply -n argocd --server-side --force-conflicts -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  install-argo-rollouts:
    desc: "Install Argo Rollouts in the cluster"
    cmds:
      - kubectl create namespace argo-rollouts
      - kubectl apply -n argo-rollouts -f https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml
  install-argo-rollouts-plugin:
    desc: "Install the Argo Rollouts plugin for Argo CD"
    cmds:
      - curl -LO https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-linux-amd64
      - chmod +x ./kubectl-argo-rollouts-linux-amd64
      - sudo mv ./kubectl-argo-rollouts-linux-amd64 /usr/local/bin/kubectl-argo-rollouts
      - kubectl argo rollouts version
  apply-crds:
    desc: "Apply the CRDs for Argo CD applications"
    cmds:
      - kubectl apply -f crds/gateway-api-crds.yaml
  apply-root-app:
    desc: "Apply the root Argo CD application"
    cmds:
      - kubectl apply -f argocd/app-project-platform.yaml
      - kubectl apply -f argocd/app-project-ml-server.yaml
      - kubectl apply -f argocd/root-app.yaml
  get-argocd-pw:
    desc: "Get the initial admin password for Argo CD"
    cmds:
      - argocd admin initial-password -n argocd
  open-argocd-ui:
    desc: "Open the Argo CD UI in the browser"
    cmds:
      - kubectl port-forward svc/argocd-server -n argocd 8080:443