apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../common/MigrationJob.yaml
patches:
  - path: patches/HTTPRoute.yaml
images:
  - name: igorsantarek/ml_server
    newTag: 0.9.3-0020-g2543aec