apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-staging
  namespace: argocd
spec:
  project: frontend
  source:
    repoURL: https://github.com/jegor377/mlops-project.git
    path: k8s/services/frontend/overlays/staging
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend-project-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true