apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-server-production
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: ml-server
  source:
    repoURL: https://github.com/jegor377/mlops-project
    path: k8s/services/server/overlays/production
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-project-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true