apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 38.0.2
    helm:
      releaseName: traefik
      valuesObject:
        logs:
          access:
            enabled: true
        # we enable gateway-api features
        providers:
          kubernetesGateway:
            enabled: true
            experimentalChannel: false
        # we disable gateway-api defaults because we want to provide our own
        gatewayClass:
          enabled: false
        # we disable gateway-api defaults because we want to provide our own
        gateway:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true