version: 3

tasks:
  run-local:
    desc: "Run the mlops server locally"
    dir: src
    cmds:
      - uv run uvicorn server.main:app --reload
  test-not-slow:
    desc: "Run the not slow tests"
    cmds:
      - uv run pytest -m "not slow"
  test-slow:
    desc: "Run the slow tests"
    cmds:
      - uv run pytest -m "slow"
  build-image:
    desc: "Build the mlops server docker image"
    cmds:
      - docker build -t {{.IMAGE_REPO}}:latest .
  run-docker:
    desc: "Run the mlops server container locally"
    cmds:
      - docker run -d -p 8000:8000 {{.IMAGE_REPO}}:latest
