version: 3

tasks:
  run-local:
    desc: "Run the mlops server locally"
    dir: src
    cmds:
      - uv run uvicorn main:app --reload
  test-local:
    desc: "Run the local tests"
    cmds:
      - uv run pytest
  build-image:
    desc: "Build the mlops server docker image"
    cmds:
      - docker build -t igorsantarek/ml_server:latest .
  run-docker:
    desc: "Run the mlops server container locally"
    cmds:
      - docker run -d -p 8000:8000 igorsantarek/ml_server:latest
