version: '3'

tasks:
  create-cluster:
    desc: "Create the dev kind cluster"
    cmds:
      - kind create cluster --config kind-config.yaml
  setup:
    desc: "Install the Gateway API CRDs"
    cmds:
      - kubectl apply --server-side -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/standard-install.yaml
      - helm repo add traefik https://traefik.github.io/charts
      - helm repo update
      - helm install traefik traefik/traefik --values traefik-values.yaml -n traefik --create-namespace
  apply-base:
    desc: "Apply the base k8s manifests"
    cmds:
      - kubectl apply -f base/Namespace.yaml
      - kubectl apply -f base/Deployment.yaml
      - kubectl apply -f base/Service.yaml
      - kubectl apply -f base/Gateway.yaml
      - kubectl apply -f base/HTTPRoute.yaml
  delete-cluster:
    desc: "Delete the dev kind cluster"
    cmds:
      - kind delete cluster
  delete-namespace:
    desc: "Delete the mlops-project namespace"
    cmds:
      - kubectl delete -f base/Namespace.yaml
