version: 3


tasks:
  run-dev:
    desc: "Run the mlops server locally"
    cmds:
      - uv run uvicorn src.ml_server.main:app --reload
  test:
    desc: "Run the not slow tests"
    env:
      ENV: development
      HOSTNAME: localhost
      FRONTEND_HOSTNAME: localhost
      DB_URI: "postgresql://postgres:postgres@127.0.0.1:8081/test_db"
      LOAD_MODEL: true
      OAUTH_STATE_SESSION_SECRET_KEY: dummy-secret-key
      SMTP__FROM_EMAIL_ADDRESS: no-reply@example.com
      GOOGLE_OAUTH2_CREDS__CLIENT_ID: dummy-client-id
      GOOGLE_OAUTH2_CREDS__CLIENT_SECRET: dummy-client-secret
      GITHUB_OAUTH2_CREDS__CLIENT_ID: dummy-client-id
      GITHUB_OAUTH2_CREDS__CLIENT_SECRET: dummy-client-secret
      FAIL_FAST: false
    cmds:
      - uv run pytest {{if eq .FAIL_FAST "true"}}--maxfail=1 {{end}}{{.CLI_ARGS | default ""}}
  build-image:
    desc: "Build the mlops server docker image"
    cmds:
      - docker build -t {{.SERVER_IMAGE_REPO}}:latest .
  run-docker:
    desc: "Run the mlops server container locally"
    vars:
      HOSTNAME: mailpit
      SMTP_HOST: 127.0.0.1
      SMTP_PORT: 1025
      SMTP_USE_CREDENTIALS: false
      SMTP_VALIDATE_CERTS: false
      SMTP_FROM: no-reply@example.com
      SMTP_STARTTLS: false
      SMTP_SSL_TLS: false
    cmds:
      - |
        docker run -d -p 8000:8000 \
        --name ml_server \
        -e DB_URI=postgresql://postgres:postgres@postgres:5432/dev_db \
        -e LOAD_MODEL={{.LOAD_MODEL_IN_DEV}} \
        -e HOSTNAME={{.HOSTNAME}} \
        -e SMTP_HOST={{.SMTP_HOST}} \
        -e SMTP_PORT={{.SMTP_PORT}} \
        -e SMTP_USE_CREDENTIALS={{.SMTP_USE_CREDENTIALS}} \
        -e SMTP_VALIDATE_CERTS={{.SMTP_VALIDATE_CERTS}} \
        -e SMTP_FROM={{.SMTP_FROM}} \
        -e SMTP_STARTTLS={{.SMTP_STARTTLS}} \
        -e SMTP_SSL_TLS={{.SMTP_SSL_TLS}} \
        --network=mlops-network \
        {{.SERVER_IMAGE_REPO}}:latest
  push-image:
    desc: "Push the mlops server docker image to registry"
    cmds:
      - docker push {{.SERVER_IMAGE_REPO}}:latest
  run-postgres-container:
    desc: "Run a postgres container locally"
    cmds:
      - |
        docker run -d -p {{.DB_PORT}}:5432 \
        --name postgres \
        -e POSTGRES_USER=postgres \
        -e POSTGRES_PASSWORD=postgres \
        -v ./init.sql:/docker-entrypoint-initdb.d/init.sql \
        --network=mlops-network \
        postgres:latest
  rm-postgres-container:
    desc: "Remove the postgres container"
    cmds:
      - docker rm -f postgres
  create-docker-network:
    desc: "Create a docker network for the mlops server and postgres to communicate"
    cmds:
      - docker network create mlops-network
  remove-docker-network:
    desc: "Remove the docker network"
    cmds:
      - docker network rm mlops-network
  psql:
    desc: "Connect to the postgres container using psql"
    cmds:
      - psql "$DB_URI"
  alembic:
    desc: "Run alembic commands"
    cmds:
      - uv run alembic {{.CLI_ARGS}}
  upgrade-db:
    desc: "Upgrade the database to the latest version"
    cmds:
      - uv run alembic upgrade head
  new-migration:
    desc: "Create a new alembic migration"
    silent: true
    cmds:
      - |
        echo -n "Enter migration message: "
        read MIGRATION_MESSAGE
        if [ -z "$MIGRATION_MESSAGE" ]; then
          echo "Migration message cannot be empty"
          exit 1
        fi
        uv run alembic revision --autogenerate -m "$MIGRATION_MESSAGE"
  run-mailpit:
    desc: "Run the mailpit container locally"
    cmds:
      - |
        docker run -d \
        --name=mailpit \
        --restart unless-stopped \
        -p 8025:8025 \
        -p 1025:1025 \
        --network=mlops-network \
        axllent/mailpit
