version: 3


tasks:
  run-dev:
    desc: "Run the mlops server locally"
    cmds:
      - uv run uvicorn src.ml_server.main:app --reload
  test:
    desc: "Run the not slow tests"
    env:
      ENV: development
      HOSTNAME: localhost
      FRONTEND_HOSTNAME: localhost
      DB_URI: '{{.DB_URI | replace "/dev_db" "/test_db"}}'
      LOAD_MODEL: true
      OAUTH_STATE_SESSION_SECRET_KEY: dummy-secret-key
      SMTP__FROM_EMAIL_ADDRESS: no-reply@example.com
      GOOGLE_OAUTH2_CREDS__CLIENT_ID: dummy-client-id
      GOOGLE_OAUTH2_CREDS__CLIENT_SECRET: dummy-client-secret
      GITHUB_OAUTH2_CREDS__CLIENT_ID: dummy-client-id
      GITHUB_OAUTH2_CREDS__CLIENT_SECRET: dummy-client-secret
      FAIL_FAST: true
    cmds:
      - uv run pytest {{if eq .FAIL_FAST "true"}}--maxfail=1 {{end}}{{.CLI_ARGS | default ""}}
  build-image:
    desc: "Build the mlops server docker image"
    cmds:
      - docker build -t {{.SERVER_IMAGE_REPO}}:latest .
  run-docker:
    desc: "Run the mlops server container locally"
    cmds:
      - |
        docker run -d -p 8000:8000 \
        --name ml_server \
        --network=mlops-network \
        {{.SERVER_IMAGE_REPO}}:latest
  push-image:
    desc: "Push the mlops server docker image to registry"
    cmds:
      - docker push {{.SERVER_IMAGE_REPO}}:latest
  run-postgres:
    desc: "Run a postgres container locally"
    cmds:
      - |
        docker run -d -p 5433:5432 \
        --name postgres \
        -e POSTGRES_USER=postgres \
        -e POSTGRES_PASSWORD=postgres \
        -v ./init.sql:/docker-entrypoint-initdb.d/init.sql \
        --network=mlops-network \
        postgres:latest
  rm-postgres:
    desc: "Remove the postgres container"
    cmds:
      - docker rm -f postgres
  create-docker-network:
    desc: "Create a docker network for the mlops server and postgres to communicate"
    cmds:
      - docker network create mlops-network
  remove-docker-network:
    desc: "Remove the docker network"
    cmds:
      - docker network rm mlops-network
  psql:
    desc: "Connect to the postgres container using psql"
    cmds:
      - psql "$DB_URI"
  alembic:
    desc: "Run alembic commands"
    cmds:
      - uv run alembic {{.CLI_ARGS}}
  upgrade-db:
    desc: "Upgrade the database to the latest version"
    cmds:
      - uv run alembic upgrade head
  new-migration:
    desc: "Create a new alembic migration"
    silent: true
    cmds:
      - |
        echo -n "Enter migration message: "
        read MIGRATION_MESSAGE
        if [ -z "$MIGRATION_MESSAGE" ]; then
          echo "Migration message cannot be empty"
          exit 1
        fi
        uv run alembic revision --autogenerate -m "$MIGRATION_MESSAGE"
  run-mailpit:
    desc: "Run the mailpit container locally"
    cmds:
      - |
        docker run -d \
        --name=mailpit \
        --restart unless-stopped \
        -p 8026:8025 \
        -p 1025:1025 \
        --network=mlops-network \
        axllent/mailpit
  run-redis:
    desc: "Run the redis container locally"
    cmds:
      - |
        docker run -d \
        --name=redis \
        --restart unless-stopped \
        -p {{.APP_REDIS_PORT}}:6379 \
        -p 8001:8001 \
        --network=mlops-network \
        redis/redis-stack \
        redis-server --requirepass "redis_pass"
