# .kluctl.yaml
targets:
  - name: staging
    args:
      cluster_name: staging
    context: kind-kind-staging
  - name: production
    args:
      cluster_name: production
    context: kind-kind-production

args:
  - name: cluster_name

discriminator: gitops-{{ args.cluster_name | slugify}}
