# https://taskfile.dev

version: '3'

tasks:
  bootstrap-kluctl-gitops:
    desc: "Bootstrap kluctl-gitops in the cluster"
    cmds:
      - task: bootstrap-kluctl-gitops-context
        vars:
          CONTEXT: kind-kind-staging
      - task: bootstrap-kluctl-gitops-context
        vars:
          CONTEXT: kind-kind-production
  bootstrap-kluctl-gitops-context:
    internal: true
    desc: "Bootstrap secrets for kluctl"
    cmds:
      - kubectx {{ .CONTEXT }}
      - kubectl apply -f namespaces/Namespace.kluctl-gitops.yaml
      - kubectl apply -f secrets/Secret.GitHub.yaml
  deploy-staging-cluster:
    desc: "Deploy to the staging cluster"
    cmds:
      - kluctl deploy -t staging
  deploy-production-cluster:
    desc: "Deploy to the production cluster"
    cmds:
      - kluctl deploy -t production
  get-webui-password:
    desc: "Get the kluctl webui admin password"
    cmds:
      - kubectl -n kluctl-gitops get secret webui-secret -o jsonpath="{.data.admin-password}" | base64 -d
  port-forward-webui:
    desc: "Port forward the kluctl webui to localhost"
    cmds:
      - kubectl -n kluctl-gitops port-forward svc/kluctl-webui 8080
