apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ml-server
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/jegor377/mlops-project.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
