"""Adds pending checkout to User model

Revision ID: 0cab034d9f8f
Revises: 93551b49c7aa
Create Date: 2026-08-30 14:31:48.476385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cab034d9f8f'
down_revision: Union[str, Sequence[str], None] = '93551b49c7aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_checkout', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_checkout')
    # ### end Alembic commands ###
