"""Adds stripe fields

Revision ID: 4f1752389775
Revises: 0cab034d9f8f
Create Date: 2026-09-07 21:43:05.178551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '4f1752389775'
down_revision: Union[str, Sequence[str], None] = '0cab034d9f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('stripe_price_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'subscriptions', ['stripe_subscription_id'])
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['stripe_customer_id'])
    op.sync_enum_values(
        enum_schema='public',
        enum_name='eventcategory',
        new_values=['pat_created', 'pat_revoked', 'auth_login', 'auth_login_failed', 'auth_logout', 'auth_oauth_login', 'account_email_verified', 'account_password_changed', 'account_verification_resent', 'billing_checkout_started', 'billing_checkout_canceled', 'billing_subscription_activated', 'billing_subscription_updated', 'billing_subscription_canceled'],
        affected_columns=[TableReference(table_schema='public', table_name='audit_log', column_name='event')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='auditcategory',
        new_values=['pat', 'auth', 'account', 'billing'],
        affected_columns=[TableReference(table_schema='public', table_name='audit_log', column_name='category')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='auditcategory',
        new_values=['pat', 'auth', 'account'],
        affected_columns=[TableReference(table_schema='public', table_name='audit_log', column_name='category')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='eventcategory',
        new_values=['pat_created', 'pat_revoked', 'auth_login', 'auth_login_failed', 'auth_logout', 'auth_oauth_login', 'account_email_verified', 'account_password_changed', 'account_verification_resent'],
        affected_columns=[TableReference(table_schema='public', table_name='audit_log', column_name='event')],
        enum_values_to_rename=[],
    )
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_column('subscriptions', 'stripe_subscription_id')
    op.drop_column('plans', 'stripe_price_id')
    # ### end Alembic commands ###
