"""Adds api_request_logs table

Revision ID: 773e0775ee20
Revises: c67de29153b8
Create Date: 2026-06-14 21:41:24.209636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773e0775ee20'
down_revision: Union[str, Sequence[str], None] = 'c67de29153b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pat_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('status_code', sa.SmallInteger(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pat_id'], ['personal_access_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_request_logs_created_at'), 'api_request_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_request_logs_user_id'), 'api_request_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_request_logs_user_id'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_created_at'), table_name='api_request_logs')
    op.drop_table('api_request_logs')
    # ### end Alembic commands ###
