"""Add revoked_at timestamp to PAT and server side defaults

Revision ID: 7a9d2834710d
Revises: 8005d87818fa
Create Date: 2026-05-05 01:18:05.305388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a9d2834710d'
down_revision: Union[str, Sequence[str], None] = '8005d87818fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_access_tokens', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_access_tokens', 'revoked_at')
    # ### end Alembic commands ###
