"""Adds plan and subscription

Revision ID: 93551b49c7aa
Revises: c67de29153b8
Create Date: 2026-08-23 20:16:58.050451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93551b49c7aa'
down_revision: Union[str, Sequence[str], None] = 'c67de29153b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'PRO', 'CUSTOM', name='plan_tier'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('requests_per_day', sa.Integer(), nullable=True),
    sa.Column('api_key_limit', sa.Integer(), nullable=True),
    sa.Column('history_days', sa.Integer(), nullable=True),
    sa.Column('priority_support', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('webhook_notifications', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('dedicated_support', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('custom_sla', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('on_prem', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELED', 'TRIALING', name='subscription_status'), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('custom_price_cents', sa.Integer(), nullable=True),
    sa.Column('custom_terms', sa.String(length=2000), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('plans')
    # ### end Alembic commands ###
