"""Changes event column to use enum in audit log

Revision ID: c67de29153b8
Revises: 3253cfad0339
Create Date: 2026-06-14 14:03:04.351716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67de29153b8'
down_revision: Union[str, Sequence[str], None] = '3253cfad0339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

event_enum = sa.Enum(
    'pat_created',
    'pat_revoked',
    'auth_login',
    'auth_login_failed',
    'auth_logout',
    'auth_oauth_login',
    'account_email_verified',
    'account_password_changed',
    'account_verification_resent',
    name='eventcategory'
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    event_enum.create(op.get_bind(), checkfirst=True)
    
    op.alter_column('audit_log', 'event',
                existing_type=sa.VARCHAR(length=64),
                type_=event_enum,
                postgresql_using="event::eventcategory",
                existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'event',
                existing_type=sa.Enum('pat_created', 'pat_revoked', 'auth_login', 'auth_login_failed', 'auth_logout', 'auth_oauth_login', 'account_email_verified', 'account_password_changed', 'account_verification_resent', name='eventcategory'),
                type_=sa.VARCHAR(length=64),
                existing_nullable=False)
    
    event_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
