vars:
  - file: metallb/config/{{ args.environment }}.yaml

deployments:
  - path: gateway-api-crds
    waitReadiness: true   # CRDs established
  - path: metallb
    waitReadiness: true
  - path: traefik
