# https://taskfile.dev

version: '3'

tasks:
  plan:
    desc: "Plan infrastructure changes using Terraform"
    cmds:
      - terraform init
      - terraform plan
  apply:
    desc: "Apply infrastructure changes using Terraform"
    cmds:
      - terraform init
      - terraform apply -auto-approve
  destroy:
    desc: "Destroy infrastructure using Terraform"
    cmds:
      - terraform init
      - terraform destroy
  fmt:
    desc: "Format Terraform code"
    cmds:
      - terraform fmt
  update:
    desc: "Update Terraform providers and modules"
    cmds:
      - terraform init -upgrade
  validate:
    desc: "Validate Terraform configuration"
    cmds:
      - terraform validate