- op: replace
  path: /apiVersion
  value: apps/v1
- op: replace
  path: /kind
  value: Deployment
- op: remove
  path: /spec/strategy
- op: add
  path: /spec/selector
  value:
    matchLabels:
      app: frontend