apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ml-server-dev
resources:
  - ../../base
  - manifests/Namespace.yaml
  - manifests/MailpitDeployment.yaml
  - manifests/MailpitService.yaml
patches:
  - path: patches/Gateway.yaml
    target:
      group: gateway.networking.k8s.io
      version: v1
      kind: Gateway
      name: ml-server-gw
  - path: patches/Rollout.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: ml-server
  - path: patches/HTTPRoute.yaml
    target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: ml-server-route
images:
  - name: igorsantarek/ml_server
    newTag: latest