name: Build & Push Docker image

on:
  push:
    branches: [ "main" ]
    paths:
      - "ml_server/**"
      - "!ml_server/src/ml_server/__init__.py"
      - "frontend/**"
      - "!frontend/node_modules/**"
      - "!frontend/.react-router/**"
      - "!frontend/README.md"
    tags:
      - "**@[0-9]*.[0-9]*.[0-9]*"

permissions:
  contents: write

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set-output.outputs.services }}
      environment: ${{ steps.set-output.outputs.environment }}
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Paths Changes Filter
      uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
      id: filter
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filters: |
          ml_server:
            - "ml_server/**"
          frontend:
            - "frontend/**"
    - name: Set Output
      id: set-output
      run: |
        if [[ "${{ github.ref_type }}" == "tag" ]]; then
          tag="${GITHUB_REF_NAME}"
          svc="${tag%%@*}"
          echo "services=[\"$svc\"]" >> "$GITHUB_OUTPUT"
          echo "environment=production" >> "$GITHUB_OUTPUT"
        else
          echo 'services=${{ steps.filter.outputs.changes }}' >> "$GITHUB_OUTPUT"
          echo 'environment=staging' >> "$GITHUB_OUTPUT"
        fi

  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ needs.filter.outputs.services != '[]' && needs.filter.outputs.services != '' }}
    needs: filter
    strategy:
      matrix:
        service: ${{ fromJson(needs.filter.outputs.services) }}
      fail-fast: false
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        fetch-depth: 0
    - name: Install Task
      uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
      with:
        version: 3.x
    - name: Log in to Docker Hub
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Compute image tag
      id: image-tag
      env:
        ENVIRONMENT: ${{ needs.filter.outputs.environment }}
        SERVICE: ${{ matrix.service }}
      run: |
        if [[ "$ENVIRONMENT" == "production" ]]; then
          IMAGE_TAG=$(task -s utils:generate-version-tag -- $SERVICE)
          VERSION=$(task -s utils:generate-version -- $SERVICE)
        else # if on push to main branch
          IMAGE_TAG=$(task -s utils:generate-extended-version-tag -- $SERVICE)
          VERSION=$(task -s utils:generate-extended-version -- $SERVICE)
        fi
        echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      with:
        driver: docker-container
    - name: Build and push Docker image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: ${{ matrix.service }}
        push: ${{ !env.ACT }}
        tags: ${{ steps.image-tag.outputs.image_tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Update Kubernetes manifests with new image tag
      if: ${{ !env.ACT }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        for i in {1..5}; do
          git pull --rebase origin main
          task utils:update-image-tags SERVICE=${{ matrix.service }} NEW_TAG=${{ steps.image-tag.outputs.version }} ENVIRONMENT=${{ needs.filter.outputs.environment }}
          git add k8s/services/${{ matrix.service }}/overlays/*/kustomization.yaml
          git commit -m "chore: Update image version to ${{ steps.image-tag.outputs.version }} on ${{ needs.filter.outputs.environment }} environment in ${{ matrix.service }} service" && \
          git push origin HEAD:main && break || git reset HEAD~1
          git checkout -- .
          sleep_time=$((RANDOM % 10 + 3))
          echo "Push failed, retrying in $sleep_time seconds..."
          sleep $sleep_time
        done